# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/dariusgiannoli/Desktop/LIS-GUI/Main_GUI/launcher_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LauncherWindow(object):
    def setupUi(self, LauncherWindow):
        LauncherWindow.setObjectName("LauncherWindow")
        LauncherWindow.resize(500, 400)
        self.centralwidget = QtWidgets.QWidget(LauncherWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.subtitleLabel = QtWidgets.QLabel(self.centralwidget)
        self.subtitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.verticalLayout.addWidget(self.subtitleLabel)
        self.connectionGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.connectionGroupBox.setObjectName("connectionGroupBox")
        self.connectionLayout = QtWidgets.QHBoxLayout(self.connectionGroupBox)
        self.connectionLayout.setContentsMargins(15, 15, 15, 15)
        self.connectionLayout.setSpacing(15)
        self.connectionLayout.setObjectName("connectionLayout")
        self.statusIndicator = QtWidgets.QLabel(self.connectionGroupBox)
        self.statusIndicator.setObjectName("statusIndicator")
        self.connectionLayout.addWidget(self.statusIndicator)
        self.statusText = QtWidgets.QLabel(self.connectionGroupBox)
        self.statusText.setObjectName("statusText")
        self.connectionLayout.addWidget(self.statusText)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.connectionLayout.addItem(spacerItem)
        self.connectionButton = QtWidgets.QPushButton(self.connectionGroupBox)
        self.connectionButton.setMinimumSize(QtCore.QSize(140, 35))
        self.connectionButton.setObjectName("connectionButton")
        self.connectionLayout.addWidget(self.connectionButton)
        self.verticalLayout.addWidget(self.connectionGroupBox)
        self.modulesGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.modulesGroupBox.setObjectName("modulesGroupBox")
        self.modulesLayout = QtWidgets.QVBoxLayout(self.modulesGroupBox)
        self.modulesLayout.setContentsMargins(15, 15, 15, 15)
        self.modulesLayout.setSpacing(15)
        self.modulesLayout.setObjectName("modulesLayout")
        self.droneControlButton = QtWidgets.QPushButton(self.modulesGroupBox)
        self.droneControlButton.setObjectName("droneControlButton")
        self.modulesLayout.addWidget(self.droneControlButton)
        self.waveformDesignerButton = QtWidgets.QPushButton(self.modulesGroupBox)
        self.waveformDesignerButton.setObjectName("waveformDesignerButton")
        self.modulesLayout.addWidget(self.waveformDesignerButton)
        self.patternGuiButton = QtWidgets.QPushButton(self.modulesGroupBox)
        self.patternGuiButton.setObjectName("patternGuiButton")
        self.modulesLayout.addWidget(self.patternGuiButton)
        self.verticalLayout.addWidget(self.modulesGroupBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        LauncherWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LauncherWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 22))
        self.menubar.setObjectName("menubar")
        LauncherWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LauncherWindow)
        self.statusbar.setObjectName("statusbar")
        LauncherWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LauncherWindow)
        QtCore.QMetaObject.connectSlotsByName(LauncherWindow)

    def retranslateUi(self, LauncherWindow):
        _translate = QtCore.QCoreApplication.translate
        LauncherWindow.setWindowTitle(_translate("LauncherWindow", "Haptic Interface Launcher"))
        LauncherWindow.setStyleSheet(_translate("LauncherWindow", "QMainWindow {\n"
"    background-color: #f5f5f5;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 15px;\n"
"    font-size: 14px;\n"
"    min-height: 40px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3d8b40;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #cccccc;\n"
"    color: #666666;\n"
"}\n"
"\n"
"QLabel#titleLabel {\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"    color: #333333;\n"
"    margin: 20px 0px;\n"
"}\n"
"\n"
"QLabel#subtitleLabel {\n"
"    font-size: 14px;\n"
"    color: #666666;\n"
"    margin-bottom: 30px;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    font-weight: bold;\n"
"    border: 2px solid #cccccc;\n"
"    border-radius: 8px;\n"
"    margin-top: 10px;\n"
"    padding-top: 10px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 5px 0 5px;\n"
"}"))
        self.titleLabel.setText(_translate("LauncherWindow", "Haptic Interface Control Center"))
        self.subtitleLabel.setText(_translate("LauncherWindow", "Connect your USB device and launch the desired interface module"))
        self.connectionGroupBox.setTitle(_translate("LauncherWindow", "Device Connection"))
        self.statusIndicator.setText(_translate("LauncherWindow", "●"))
        self.statusIndicator.setStyleSheet(_translate("LauncherWindow", "color: #f44336; font-size: 16px; font-weight: bold;"))
        self.statusIndicator.setToolTip(_translate("LauncherWindow", "Connection Status"))
        self.statusText.setText(_translate("LauncherWindow", "Disconnected"))
        self.statusText.setStyleSheet(_translate("LauncherWindow", "color: #666; font-size: 12px; margin-left: 5px; margin-right: 10px;"))
        self.connectionButton.setText(_translate("LauncherWindow", "Connect USB Device"))
        self.connectionButton.setStyleSheet(_translate("LauncherWindow", "QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    padding: 8px 16px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #3d8b40;\n"
"}"))
        self.modulesGroupBox.setTitle(_translate("LauncherWindow", "Interface Modules"))
        self.droneControlButton.setText(_translate("LauncherWindow", "🚁 Drone Control GUI"))
        self.droneControlButton.setToolTip(_translate("LauncherWindow", "Launch the main drone control interface with 3D view, 2D map, and actuator controls"))
        self.waveformDesignerButton.setText(_translate("LauncherWindow", "🌊 Waveform Designer"))
        self.waveformDesignerButton.setToolTip(_translate("LauncherWindow", "Launch the Universal Event Designer for creating custom haptic waveforms"))
        self.patternGuiButton.setText(_translate("LauncherWindow", "📊 Pattern GUI"))
        self.patternGuiButton.setToolTip(_translate("LauncherWindow", "Launch the Haptic Pattern GUI for creating and testing vibration patterns"))
