# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/dariusgiannoli/Desktop/f/Pattern_Generator/save_pattern_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SavePatternDialog(object):
    def setupUi(self, SavePatternDialog):
        SavePatternDialog.setObjectName("SavePatternDialog")
        SavePatternDialog.resize(400, 300)
        SavePatternDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(SavePatternDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(SavePatternDialog)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.nameEdit = QtWidgets.QLineEdit(SavePatternDialog)
        self.nameEdit.setObjectName("nameEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameEdit)
        self.descriptionLabel = QtWidgets.QLabel(SavePatternDialog)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.descriptionLabel)
        self.descriptionEdit = QtWidgets.QTextEdit(SavePatternDialog)
        self.descriptionEdit.setMaximumSize(QtCore.QSize(16777215, 80))
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.descriptionEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.previewGroup = QtWidgets.QGroupBox(SavePatternDialog)
        self.previewGroup.setObjectName("previewGroup")
        self.previewLayout = QtWidgets.QVBoxLayout(self.previewGroup)
        self.previewLayout.setObjectName("previewLayout")
        self.previewText = QtWidgets.QTextEdit(self.previewGroup)
        self.previewText.setMaximumSize(QtCore.QSize(16777215, 120))
        self.previewText.setReadOnly(True)
        self.previewText.setObjectName("previewText")
        self.previewLayout.addWidget(self.previewText)
        self.verticalLayout.addWidget(self.previewGroup)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.cancelButton = QtWidgets.QPushButton(SavePatternDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonLayout.addWidget(self.cancelButton)
        self.saveButton = QtWidgets.QPushButton(SavePatternDialog)
        self.saveButton.setEnabled(False)
        self.saveButton.setObjectName("saveButton")
        self.buttonLayout.addWidget(self.saveButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(SavePatternDialog)
        self.cancelButton.clicked.connect(SavePatternDialog.reject) # type: ignore
        self.saveButton.clicked.connect(SavePatternDialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SavePatternDialog)

    def retranslateUi(self, SavePatternDialog):
        _translate = QtCore.QCoreApplication.translate
        SavePatternDialog.setWindowTitle(_translate("SavePatternDialog", "Save Pattern Configuration"))
        self.nameLabel.setText(_translate("SavePatternDialog", "Pattern Name:"))
        self.nameEdit.setPlaceholderText(_translate("SavePatternDialog", "Enter pattern name..."))
        self.descriptionLabel.setText(_translate("SavePatternDialog", "Description:"))
        self.descriptionEdit.setPlaceholderText(_translate("SavePatternDialog", "Optional description..."))
        self.previewGroup.setTitle(_translate("SavePatternDialog", "Configuration Preview"))
        self.cancelButton.setText(_translate("SavePatternDialog", "Cancel"))
        self.saveButton.setText(_translate("SavePatternDialog", "Save"))
